steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "➡️ Setting safe directory for git"
        git config --global --add safe.directory /var/www/html/cicd-static-site
        echo "✅ Safe directory set"

        echo "➡️ Connecting to VM and pulling code"
        gcloud compute ssh manish_p@ci-cd \
          --zone=asia-south1-b \
          --command="cd /var/www/html/superset && git pull origin main && sudo cp index.html /var/www/html/"
"
options:
  logging: CLOUD_LOGGING_ONLY
