steps:
  # Step 1: Copy code to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '.', 'gs://my-app-artifacts/']

  # Step 2: SSH into VM and deploy (e.g., pull latest code)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - 'vm-instance-name'
      - '--zone=us-central1-a'
      - '--command=sudo gsutil cp gs://my-app-artifacts/main.py /var/www/html/']
    timeout: 600s
