steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '.', 'gs://superset-artifacts/']

  - name: 'gcr.io/cloud-builders/busybox'
    args: ['sleep', '30']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - 'dev-superset'
      - '--zone=asia-south1-c'
      - '--command=sudo gsutil cp gs://superset-artifacts/intex.html /var/www/html/']
    timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
